### save short
POST http://localhost:5000/api/shorts
Content-Type: application/json

{
  "videoUrl": "https://example.com/video.mp4",
  "title": "Sample Title",
  "tags": ["tag1", "tag2"]
}


### get all shorts
GET http://localhost:5000/api/shorts

### get short by id
GET http://localhost:5000/api/shorts/1